// HindiAnimeStuff — catalog data
// Each entry links to the official platform that distributes that title.
const ANIME_DATA = [
  {
    id: "overlord-s1",
    title: "Overlord",
    season: "Season 1",
    thumb: "https://i.imgur.com/Lznc1Mc.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Japanese · Hindi Dub",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p / 480p",
    rating: "7.9",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GR751KNZY/overlord",
    synopsis: "A veteran gamer finds himself trapped in his favorite MMORPG as his powerful in-game character, ruling a world that has suddenly become disturbingly real."
  },
  {
    id: "overlord-s2",
    title: "Overlord",
    season: "Season 2",
    thumb: "https://i.imgur.com/bLY5cXU.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p",
    rating: "7.8",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GR751KNZY/overlord",
    synopsis: "Ainz Ooal Gown continues to expand his dominion, navigating politics, war, and the loyalty of his fiercely devoted guardians."
  },
  {
    id: "overlord-s3",
    title: "Overlord",
    season: "Season 3",
    thumb: "https://i.imgur.com/EjQoKYD.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p",
    rating: "7.7",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GR751KNZY/overlord",
    synopsis: "Ainz's empire grows as he turns his attention to the Lizardman tribes and a kingdom unprepared for what's coming."
  },
  {
    id: "overlord-s4",
    title: "Overlord",
    season: "Season 4",
    thumb: "https://i.imgur.com/Bs2hVbH.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p",
    rating: "7.6",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GR751KNZY/overlord",
    synopsis: "The final season sees the Sorcerer Kingdom's influence reach its peak as old enemies and new threats converge."
  },
  {
    id: "arifureta-s1",
    title: "Arifureta: From Commonplace to World's Strongest",
    season: "Season 1",
    thumb: "https://i.ibb.co/20SVhRvC/Zv-BS8-Nk-H.jpg",
    genres: ["Animation", "Fantasy", "Romance"],
    run: "TV Series (2019–2025)",
    runtime: "24 min",
    language: "Japanese · English · Tamil · Telugu · Hindi Dub",
    episodes: 13,
    subtitle: "English Dialogue + Dubtitle (ASS, Softcoded)",
    quality: "720p HD",
    rating: "6.7",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GG5H5XQVK/arifureta-from-commonplace-to-worlds-strongest",
    synopsis: "An ordinary student is transported to another world and left behind by his class, only to claw his way to power through a hostile labyrinth."
  },
  {
    id: "arifureta-s2",
    title: "Arifureta: From Commonplace to World's Strongest",
    season: "Season 2",
    thumb: "https://i.ibb.co/4ZY2Gp0Q/TUVMp-HLS.jpg",
    genres: ["Animation", "Fantasy", "Romance"],
    run: "TV Series (2019–2025)",
    runtime: "24 min",
    language: "Japanese · English · Tamil · Telugu · Hindi Dub",
    episodes: 13,
    subtitle: "English Dialogue + Dubtitle (ASS, Softcoded)",
    quality: "720p HD",
    rating: "6.6",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GG5H5XQVK/arifureta-from-commonplace-to-worlds-strongest",
    synopsis: "Hajime and his party push deeper into a world of monsters and rival nations as stakes rise beyond the dungeon walls."
  },
  {
    id: "solo-leveling-s1",
    title: "Solo Leveling",
    season: "Season 1",
    thumb: "https://i.ibb.co/xtNqdJty/QG2-GBh-LS.jpg",
    genres: ["Action", "Adventure"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 12,
    subtitle: "English",
    quality: "720p HD",
    rating: "8.3",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GVDHX7QQR/solo-leveling",
    synopsis: "The weakest hunter alive discovers a mysterious system that lets him grow stronger than anyone has ever imagined."
  },
  {
    id: "solo-leveling-s2",
    title: "Solo Leveling: Arise from the Shadow",
    franchise: "Solo Leveling",
    season: "Season 2",
    thumb: "https://i.ibb.co/7N4bSmKg/ng30AQgp.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 13,
    subtitle: "English",
    quality: "480p / 720p / 1080p",
    rating: "8.4",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GVDHX7QQR/solo-leveling",
    synopsis: "Sung Jinwoo rises through the ranks of hunters as the shadow monarch's true power begins to surface."
  },
  {
    id: "cheat-skill-s1",
    title: "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too",
    season: "Season 1",
    thumb: "https://i.ibb.co/wFtnMdjs/AH1-Gb-NLR.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 13,
    subtitle: "English",
    quality: "720p",
    rating: "6.4",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/G79H23VNQ/i-got-a-cheat-skill-in-another-world-and-became-unrivaled-in-the-real-world-too",
    synopsis: "A bullied student gains overwhelming power in another world, and brings it home to turn the tables on his old life."
  },
  {
    id: "bye-bye-earth-s1",
    title: "Bye Bye, Earth",
    season: "Season 1",
    thumb: "https://i.ibb.co/sJzHVnZF/MEIr-DIPA.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 10,
    subtitle: "English",
    quality: "720p",
    rating: "6.7",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GVDHX9R9R/bye-bye-earth",
    synopsis: "In a world split into kingdoms ruled by women, a wandering warrior searches for someone strong enough to challenge fate itself."
  },
  {
    id: "bye-bye-earth-s2",
    title: "Bye Bye, Earth",
    season: "Season 2",
    thumb: "https://i.ibb.co/XZvgSfkv/kdq0-Kjj-L.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 10,
    subtitle: "English",
    quality: "720p",
    rating: "6.2",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GVDHX9R9R/bye-bye-earth",
    synopsis: "The journey continues as old truths unravel and new alliances form on the road to the world's edge."
  },
  {
    id: "ranma-s1",
    title: "Ranma ½ (2024)",
    season: "Season 1",
    thumb: "https://i.ibb.co/1fPxTzhq/m4gneeo9.jpg",
    genres: ["Action", "Comedy", "Romance"],
    run: "TV Series (2024)",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "7.8",
    platform: "Netflix",
    platformUrl: "https://www.netflix.com/title/81725149",
    synopsis: "A martial artist cursed to turn into a girl when splashed with cold water navigates love, rivalry, and chaos at home."
  },
  {
    id: "ranma-s2",
    title: "Ranma ½ (2024)",
    season: "Season 2",
    thumb: "https://i.ibb.co/nNZQf38n/U98Vgxdb.jpg",
    genres: ["Action", "Comedy", "Romance"],
    run: "TV Series (2024)",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "7.8",
    platform: "Netflix",
    platformUrl: "https://www.netflix.com/title/81725149",
    synopsis: "Ranma's chaotic life continues with new challengers, deeper rivalries, and no shortage of cold water."
  },
  {
    id: "aot-s1",
    title: "Attack on Titan",
    season: "Season 1",
    thumb: "https://i.ibb.co/Fbw71Z9L/Kay-MG2j-T.jpg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 25,
    subtitle: "English",
    quality: "480p / 720p / 1080p",
    rating: "9.1",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan",
    synopsis: "Humanity huddles behind massive walls to survive against man-eating Titans, until one boy vows to wipe them all out."
  },
  {
    id: "aot-s2",
    title: "Attack on Titan",
    season: "Season 2",
    thumb: "https://i.ibb.co/cXNjh1DQ/u-OU2-F47j.jpg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "9.1",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan",
    synopsis: "Secrets behind the Titans and the walls themselves begin to surface as old loyalties are tested."
  },
  {
    id: "aot-s3",
    title: "Attack on Titan",
    season: "Season 3",
    thumb: "https://i.ibb.co/tpjpvRq2/Di-Alifd3.jpg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 22,
    subtitle: "English",
    quality: "720p",
    rating: "9.1",
    platform: "Prime Video",
    platformUrl: "https://www.primevideo.com/detail/Attack-on-Titan/0V2YOZ5RBVK3VVSCO5OYY9SPNT",
    synopsis: "A government conspiracy unravels as the survey corps uncover the true history hidden beneath the walls."
  },
  {
    id: "aot-s4",
    title: "Attack on Titan",
    season: "Season 4",
    thumb: "https://i.ibb.co/VYT203qT/FGj-Vxb02.jpg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 28,
    subtitle: "English",
    quality: "720p",
    rating: "9.1",
    platform: "Prime Video",
    platformUrl: "https://www.primevideo.com/detail/Attack-on-Titan/0V2YOZ5RBVK3VVSCO5OYY9SPNT",
    synopsis: "The final chapter brings the war to its devastating conclusion as Eren's true intentions are revealed."
  },
  {
    id: "jjk-s1",
    title: "Jujutsu Kaisen",
    season: "Season 1",
    thumb: "https://i.ibb.co/Z6DZP1cH/b-Nd-PMtg-Q.jpg",
    genres: ["Action", "Comedy", "Drama", "Fantasy", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.6",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GY5P48XEY/jujutsu-kaisen",
    synopsis: "A high schooler swallows a cursed object to save his friends and is drawn into the hidden world of curses and exorcists."
  },
  {
    id: "jjk-s2",
    title: "Jujutsu Kaisen",
    season: "Season 2",
    thumb: "https://i.ibb.co/WvbQR3B2/fl8-Vh-Swq.jpg",
    genres: ["Action", "Comedy", "Drama", "Fantasy", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 23,
    subtitle: "English",
    quality: "720p",
    rating: "8.8",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GY5P48XEY/jujutsu-kaisen",
    synopsis: "The Hidden Inventory and Shibuya Incident arcs unfold, reshaping the world of jujutsu sorcerers forever."
  },
  {
    id: "jjk-s3",
    title: "Jujutsu Kaisen",
    season: "Season 3",
    thumb: "https://i.ibb.co/wZMFGpW2/m1ZZTknr.jpg",
    genres: ["Action", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · Bangla · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "8.7",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GY5P48XEY/jujutsu-kaisen",
    synopsis: "The Culling Game arc begins, pitting sorcerers against each other in a deadly game with the fate of the world at stake."
  },
  {
    id: "jjk-0",
    title: "Jujutsu Kaisen 0",
    season: "Movie",
    thumb: "https://i.ibb.co/yLfdw1Y/i7rj-Db-Xo.jpg",
    genres: ["Action", "Supernatural"],
    run: "Movie",
    runtime: "1 hr 44 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: null,
    subtitle: "English",
    quality: "720p",
    rating: "7.8",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GVDHX18ZR/jujutsu-kaisen-0",
    synopsis: "A young sorcerer cursed by a childhood promise must choose between vengeance and the bonds he forms at Jujutsu High."
  },
  {
    id: "slime-s1",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 1",
    thumb: "https://i.ibb.co/1fgnFRqm/ni-Qlb-UPs.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.2",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GG5H5XQ8R/that-time-i-got-reincarnated-as-a-slime",
    synopsis: "Reincarnated as a slime in a fantasy world, an ordinary man builds a nation from scratch with unexpected power and diplomacy."
  },
  {
    id: "slime-s2",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 2",
    thumb: "https://i.ibb.co/1f6bFHYt/ZDb-E5wa-G.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.2",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GG5H5XQ8R/that-time-i-got-reincarnated-as-a-slime",
    synopsis: "Rimuru's nation of Tempest draws the attention of empires and threats far beyond the forest it began in."
  },
  {
    id: "slime-s3",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 3",
    thumb: "https://i.ibb.co/93rPL4xM/a-Mk-MBq-Uv.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.2",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GG5H5XQ8R/that-time-i-got-reincarnated-as-a-slime",
    synopsis: "Tempest's rise to nationhood accelerates as Rimuru faces rivals who see his peace as a threat."
  },
  {
    id: "slime-s4",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 4",
    thumb: "https://i.ibb.co/0ptkG0NS/y-Tml-YI3-B.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: null,
    subtitle: "English",
    quality: "480p / 720p / 1080p",
    rating: "8.2",
    platform: "Crunchyroll",
    platformUrl: "https://www.crunchyroll.com/series/GG5H5XQ8R/that-time-i-got-reincarnated-as-a-slime",
    synopsis: "The next chapter of Tempest's story continues to expand the world Rimuru has built."
  }
];
